interface DelayedAnimationHolder {
    constructor(keyframes, options)
    assign(element): DelayedAnimation
}
interface DelayedAnimation {
    constructor(keyframes, options, element)
    currentTime: number;
    effect: KeyframeEffect
    finished: Promise<any>
    id: string
    pending: boolean
    playState: string
    playbackRate: number
    ready: Promise<any>
    startTime: number
    timeline: AnimationTimeline | DocumentTimeline
    oncancel: Function
    onfinish: Function
    cancel(): void
    finish(): void
    pause(): void
    play(): void
    reverse(): void
    updatePlaybackRate(): void
}
interface _Animator {
    reset(): _Animator
    repeat(count): _Animator
    start(duration, opts?): Animation | DelayedAnimation
    render(duration, opts?): DelayedAnimationHolder | DelayedAnimation
    transform(x, y): _Animator
    transform(x, y, z): _Animator
    duration(time): _Animator
    easing(easing_type): _Animator
    next(): _Animator
    alignContent(...args): _Animator
    alignItems(...args): _Animator
    alignSelf(...args): _Animator
    alignmentBaseline(...args): _Animator
    all(...args): _Animator
    animation(...args): _Animator
    animationDelay(...args): _Animator
    animationDirection(...args): _Animator
    animationDuration(...args): _Animator
    animationFillMode(...args): _Animator
    animationIterationCount(...args): _Animator
    animationName(...args): _Animator
    animationPlayState(...args): _Animator
    animationTiming(...args): _Animator
    backfaceVisibility(...args): _Animator
    background(...args): _Animator
    backgroundAttachment(...args): _Animator
    backgroundBlendMode(...args): _Animator
    backgroundClip(...args): _Animator
    backgroundColor(...args): _Animator
    backgroundImage(...args): _Animator
    backgroundOrigin(...args): _Animator
    backgroundPosition(...args): _Animator
    backgroundPositionX(...args): _Animator
    backgroundPositionY(...args): _Animator
    backgroundRepeat(...args): _Animator
    backgroundRepeatX(...args): _Animator
    backgroundRepeatY(...args): _Animator
    backgroundSize(...args): _Animator
    baselineShift(...args): _Animator
    blockSize(...args): _Animator
    border(...args): _Animator
    borderBlockEnd(...args): _Animator
    borderBlockEndColor(...args): _Animator
    borderBlockEndStyle(...args): _Animator
    borderBlockEndWidth(...args): _Animator
    borderBlockStart(...args): _Animator
    borderBlockStartColor(...args): _Animator
    borderBlockStartStyle(...args): _Animator
    borderBlockStartWidth(...args): _Animator
    borderBottom(...args): _Animator
    borderBottomColor(...args): _Animator
    borderBottomLeftRadius(...args): _Animator
    borderBottomRightRadius(...args): _Animator
    borderBottomStyle(...args): _Animator
    borderBottomWidth(...args): _Animator
    borderCollapse(...args): _Animator
    borderColor(...args): _Animator
    borderImage(...args): _Animator
    borderImageOutset(...args): _Animator
    borderImageRepeat(...args): _Animator
    borderImageSlice(...args): _Animator
    borderImageSource(...args): _Animator
    borderImageWidth(...args): _Animator
    borderInlineEnd(...args): _Animator
    borderInlineEndColor(...args): _Animator
    borderInlineEndStyle(...args): _Animator
    borderInlineEndWidth(...args): _Animator
    borderInlineStart(...args): _Animator
    borderInlineStartColor(...args): _Animator
    borderInlineStartStyle(...args): _Animator
    borderInlineStartWidth(...args): _Animator
    borderLeft(...args): _Animator
    borderLeftColor(...args): _Animator
    borderLeftStyle(...args): _Animator
    borderLeftWidth(...args): _Animator
    borderRadius(...args): _Animator
    borderRight(...args): _Animator
    borderRightColor(...args): _Animator
    borderRightStyle(...args): _Animator
    borderRightWidth(...args): _Animator
    borderSpacing(...args): _Animator
    borderStyle(...args): _Animator
    borderTop(...args): _Animator
    borderTopColor(...args): _Animator
    borderTopLeftRadius(...args): _Animator
    borderTopRightRadius(...args): _Animator
    borderTopStyle(...args): _Animator
    borderTopWidth(...args): _Animator
    borderWidth(...args): _Animator
    bottom(...args): _Animator
    boxShadow(...args): _Animator
    boxSizing(...args): _Animator
    breakAfter(...args): _Animator
    breakBefore(...args): _Animator
    breakInside(...args): _Animator
    bufferedRendering(...args): _Animator
    captionSide(...args): _Animator
    caretColor(...args): _Animator
    clear(...args): _Animator
    clip(...args): _Animator
    clipPath(...args): _Animator
    clipRule(...args): _Animator
    color(...args): _Animator
    colorInterpolation(...args): _Animator
    colorInterpolationFilters(...args): _Animator
    colorRendering(...args): _Animator
    columnCount(...args): _Animator
    columnFill(...args): _Animator
    columnGap(...args): _Animator
    columnRule(...args): _Animator
    columnRuleColor(...args): _Animator
    columnRuleStyle(...args): _Animator
    columnRuleWidth(...args): _Animator
    columnSpan(...args): _Animator
    columnWidth(...args): _Animator
    columns(...args): _Animator
    contain(...args): _Animator
    content(...args): _Animator
    counterIncrement(...args): _Animator
    counterReset(...args): _Animator
    cursor(...args): _Animator
    cx(...args): _Animator
    cy(...args): _Animator
    d(...args): _Animator
    direction(...args): _Animator
    display(...args): _Animator
    dominantBaseline(...args): _Animator
    emptyCells(...args): _Animator
    fill(...args): _Animator
    fillOpacity(...args): _Animator
    fillRule(...args): _Animator
    filter(...args): _Animator
    flex(...args): _Animator
    flexBasis(...args): _Animator
    flexDirection(...args): _Animator
    flexFlow(...args): _Animator
    flexGrow(...args): _Animator
    flexShrink(...args): _Animator
    flexWrap(...args): _Animator
    float(...args): _Animator
    floodColor(...args): _Animator
    floodOpacity(...args): _Animator
    font(...args): _Animator
    fontDisplay(...args): _Animator
    fontFamily(...args): _Animator
    fontFeatureSettings(...args): _Animator
    fontKerning(...args): _Animator
    fontSize(...args): _Animator
    fontStretch(...args): _Animator
    fontStyle(...args): _Animator
    fontVariant(...args): _Animator
    fontVariantCaps(...args): _Animator
    fontVariantEastAsian(...args): _Animator
    fontVariantLigatures(...args): _Animator
    fontVariantNumeric(...args): _Animator
    fontVariationSettings(...args): _Animator
    fontWeight(...args): _Animator
    gap(...args): _Animator
    grid(...args): _Animator
    gridArea(...args): _Animator
    gridAutoColumns(...args): _Animator
    gridAutoFlow(...args): _Animator
    gridAutoRows(...args): _Animator
    gridColumn(...args): _Animator
    gridColumnEnd(...args): _Animator
    gridColumnGap(...args): _Animator
    gridColumnStart(...args): _Animator
    gridGap(...args): _Animator
    gridRow(...args): _Animator
    gridRowEnd(...args): _Animator
    gridRowGap(...args): _Animator
    gridRowStart(...args): _Animator
    gridTemplate(...args): _Animator
    gridTemplateAreas(...args): _Animator
    gridTemplateColumns(...args): _Animator
    gridTemplateRows(...args): _Animator
    height(...args): _Animator
    hyphens(...args): _Animator
    imageRendering(...args): _Animator
    inlineSize(...args): _Animator
    isolation(...args): _Animator
    justifyContent(...args): _Animator
    justifyItems(...args): _Animator
    justifySelf(...args): _Animator
    left(...args): _Animator
    letterSpacing(...args): _Animator
    lightingColor(...args): _Animator
    lineBreak(...args): _Animator
    lineHeight(...args): _Animator
    listStyle(...args): _Animator
    listStyleImage(...args): _Animator
    listStylePosition(...args): _Animator
    listStyleType(...args): _Animator
    margin(...args): _Animator
    marginBlockEnd(...args): _Animator
    marginBlockStart(...args): _Animator
    marginBottom(...args): _Animator
    marginInlineEnd(...args): _Animator
    marginInlineStart(...args): _Animator
    marginLeft(...args): _Animator
    marginRight(...args): _Animator
    marginTop(...args): _Animator
    marker(...args): _Animator
    markerEnd(...args): _Animator
    markerMid(...args): _Animator
    markerStart(...args): _Animator
    mask(...args): _Animator
    maskType(...args): _Animator
    maxBlockSize(...args): _Animator
    maxHeight(...args): _Animator
    maxInlineSize(...args): _Animator
    maxWidth(...args): _Animator
    maxZoom(...args): _Animator
    minBlockSize(...args): _Animator
    minHeight(...args): _Animator
    minInlineSize(...args): _Animator
    minWidth(...args): _Animator
    minZoom(...args): _Animator
    mixBlendMode(...args): _Animator
    objectFit(...args): _Animator
    objectPosition(...args): _Animator
    offset(...args): _Animator
    offsetDistance(...args): _Animator
    offsetPath(...args): _Animator
    offsetRotate(...args): _Animator
    opacity(...args): _Animator
    order(...args): _Animator
    orientation(...args): _Animator
    orphans(...args): _Animator
    outline(...args): _Animator
    outlineColor(...args): _Animator
    outlineOffset(...args): _Animator
    outlineStyle(...args): _Animator
    outlineWidth(...args): _Animator
    overflow(...args): _Animator
    overflowAnchor(...args): _Animator
    overflowWrap(...args): _Animator
    overflowX(...args): _Animator
    overflowY(...args): _Animator
    overscrollBehavior(...args): _Animator
    overscrollBehaviorX(...args): _Animator
    overscrollBehaviorY(...args): _Animator
    padding(...args): _Animator
    paddingBlockEnd(...args): _Animator
    paddingBlockStart(...args): _Animator
    paddingBottom(...args): _Animator
    paddingInlineEnd(...args): _Animator
    paddingInlineStart(...args): _Animator
    paddingLeft(...args): _Animator
    paddingRight(...args): _Animator
    paddingTop(...args): _Animator
    page(...args): _Animator
    pageBreakAfter(...args): _Animator
    pageBreakBefore(...args): _Animator
    pageBreakInside(...args): _Animator
    paintOrder(...args): _Animator
    perspective(...args): _Animator
    perspectiveOrigin(...args): _Animator
    placeContent(...args): _Animator
    placeItems(...args): _Animator
    placeSelf(...args): _Animator
    pointerEvents(...args): _Animator
    position(...args): _Animator
    quotes(...args): _Animator
    r(...args): _Animator
    resize(...args): _Animator
    right(...args): _Animator
    rowGap(...args): _Animator
    rx(...args): _Animator
    ry(...args): _Animator
    scrollBehavior(...args): _Animator
    scrollMargin(...args): _Animator
    scrollMarginBlock(...args): _Animator
    scrollMarginBlockEnd(...args): _Animator
    scrollMarginBlockStart(...args): _Animator
    scrollMarginBottom(...args): _Animator
    scrollMarginInline(...args): _Animator
    scrollMarginInlineEnd(...args): _Animator
    scrollMarginInlineStart(...args): _Animator
    scrollMarginLeft(...args): _Animator
    scrollMarginRight(...args): _Animator
    scrollMarginTop(...args): _Animator
    scrollPadding(...args): _Animator
    scrollPaddingBlock(...args): _Animator
    scrollPaddingBlockEnd(...args): _Animator
    scrollPaddingBlockStart(...args): _Animator
    scrollPaddingBottom(...args): _Animator
    scrollPaddingInline(...args): _Animator
    scrollPaddingInlineEnd(...args): _Animator
    scrollPaddingInlineStart(...args): _Animator
    scrollPaddingLeft(...args): _Animator
    scrollPaddingRight(...args): _Animator
    scrollPaddingTop(...args): _Animator
    scrollSnapAlign(...args): _Animator
    scrollSnapStop(...args): _Animator
    scrollSnapType(...args): _Animator
    shapeImageThreshold(...args): _Animator
    shapeMargin(...args): _Animator
    shapeOutside(...args): _Animator
    shapeRendering(...args): _Animator
    size(...args): _Animator
    speak(...args): _Animator
    src(...args): _Animator
    stopColor(...args): _Animator
    stopOpacity(...args): _Animator
    stroke(...args): _Animator
    strokeDasharray(...args): _Animator
    strokeDashoffset(...args): _Animator
    strokeLinecap(...args): _Animator
    strokeLinejoin(...args): _Animator
    strokeMiterlimit(...args): _Animator
    strokeOpacity(...args): _Animator
    strokeWidth(...args): _Animator
    tabSize(...args): _Animator
    tableLayout(...args): _Animator
    textAlign(...args): _Animator
    textAlignLast(...args): _Animator
    textAnchor(...args): _Animator
    textCombineUpright(...args): _Animator
    textDecoration(...args): _Animator
    textDecorationColor(...args): _Animator
    textDecorationLine(...args): _Animator
    textDecorationSkipInk(...args): _Animator
    textDecorationStyle(...args): _Animator
    textIndent(...args): _Animator
    textOrientation(...args): _Animator
    textOverflow(...args): _Animator
    textRendering(...args): _Animator
    textShadow(...args): _Animator
    textSizeAdjust(...args): _Animator
    textTransform(...args): _Animator
    textUnderlinePosition(...args): _Animator
    top(...args): _Animator
    touchAction(...args): _Animator
    transform(...args): _Animator
    transformBox(...args): _Animator
    transformOrigin(...args): _Animator
    transformStyle(...args): _Animator
    transition(...args): _Animator
    transitionDelay(...args): _Animator
    transitionDuration(...args): _Animator
    transitionProperty(...args): _Animator
    transitionTiming(...args): _Animator
    unicodeBidi(...args): _Animator
    unicodeRange(...args): _Animator
    userSelect(...args): _Animator
    userZoom(...args): _Animator
    vectorEffect(...args): _Animator
    verticalAlign(...args): _Animator
    visibility(...args): _Animator
    webkitAlignContent(...args): _Animator
    webkitAlignItems(...args): _Animator
    webkitAlignSelf(...args): _Animator
    webkitAnimation(...args): _Animator
    webkitAnimationDelay(...args): _Animator
    webkitAnimationDirection(...args): _Animator
    webkitAnimationDuration(...args): _Animator
    webkitAnimationFillMode(...args): _Animator
    webkitAnimationIterationCount(...args): _Animator
    webkitAnimationName(...args): _Animator
    webkitAnimationPlayState(...args): _Animator
    webkitAnimationTiming(...args): _Animator
    webkitAppRegion(...args): _Animator
    webkitAppearance(...args): _Animator
    webkitBackfaceVisibility(...args): _Animator
    webkitBackgroundClip(...args): _Animator
    webkitBackgroundOrigin(...args): _Animator
    webkitBackgroundSize(...args): _Animator
    webkitBorderAfter(...args): _Animator
    webkitBorderAfterColor(...args): _Animator
    webkitBorderAfterStyle(...args): _Animator
    webkitBorderAfterWidth(...args): _Animator
    webkitBorderBefore(...args): _Animator
    webkitBorderBeforeColor(...args): _Animator
    webkitBorderBeforeStyle(...args): _Animator
    webkitBorderBeforeWidth(...args): _Animator
    webkitBorderBottomLeftRadius(...args): _Animator
    webkitBorderBottomRightRadius(...args): _Animator
    webkitBorderEnd(...args): _Animator
    webkitBorderEndColor(...args): _Animator
    webkitBorderEndStyle(...args): _Animator
    webkitBorderEndWidth(...args): _Animator
    webkitBorderHorizontalSpacing(...args): _Animator
    webkitBorderImage(...args): _Animator
    webkitBorderRadius(...args): _Animator
    webkitBorderStart(...args): _Animator
    webkitBorderStartColor(...args): _Animator
    webkitBorderStartStyle(...args): _Animator
    webkitBorderStartWidth(...args): _Animator
    webkitBorderTopLeftRadius(...args): _Animator
    webkitBorderTopRightRadius(...args): _Animator
    webkitBorderVerticalSpacing(...args): _Animator
    webkitBoxAlign(...args): _Animator
    webkitBoxDecorationBreak(...args): _Animator
    webkitBoxDirection(...args): _Animator
    webkitBoxFlex(...args): _Animator
    webkitBoxOrdinalGroup(...args): _Animator
    webkitBoxOrient(...args): _Animator
    webkitBoxPack(...args): _Animator
    webkitBoxReflect(...args): _Animator
    webkitBoxShadow(...args): _Animator
    webkitBoxSizing(...args): _Animator
    webkitClipPath(...args): _Animator
    webkitColumnBreakAfter(...args): _Animator
    webkitColumnBreakBefore(...args): _Animator
    webkitColumnBreakInside(...args): _Animator
    webkitColumnCount(...args): _Animator
    webkitColumnGap(...args): _Animator
    webkitColumnRule(...args): _Animator
    webkitColumnRuleColor(...args): _Animator
    webkitColumnRuleStyle(...args): _Animator
    webkitColumnRuleWidth(...args): _Animator
    webkitColumnSpan(...args): _Animator
    webkitColumnWidth(...args): _Animator
    webkitColumns(...args): _Animator
    webkitFilter(...args): _Animator
    webkitFlex(...args): _Animator
    webkitFlexBasis(...args): _Animator
    webkitFlexDirection(...args): _Animator
    webkitFlexFlow(...args): _Animator
    webkitFlexGrow(...args): _Animator
    webkitFlexShrink(...args): _Animator
    webkitFlexWrap(...args): _Animator
    webkitFontFeatureSettings(...args): _Animator
    webkitFontSizeDelta(...args): _Animator
    webkitFontSmoothing(...args): _Animator
    webkitHighlight(...args): _Animator
    webkitHyphenateCharacter(...args): _Animator
    webkitJustifyContent(...args): _Animator
    webkitLineBreak(...args): _Animator
    webkitLineClamp(...args): _Animator
    webkitLocale(...args): _Animator
    webkitLogicalHeight(...args): _Animator
    webkitLogicalWidth(...args): _Animator
    webkitMarginAfter(...args): _Animator
    webkitMarginAfterCollapse(...args): _Animator
    webkitMarginBefore(...args): _Animator
    webkitMarginBeforeCollapse(...args): _Animator
    webkitMarginBottomCollapse(...args): _Animator
    webkitMarginCollapse(...args): _Animator
    webkitMarginEnd(...args): _Animator
    webkitMarginStart(...args): _Animator
    webkitMarginTopCollapse(...args): _Animator
    webkitMask(...args): _Animator
    webkitMaskBoxImage(...args): _Animator
    webkitMaskBoxImageOutset(...args): _Animator
    webkitMaskBoxImageRepeat(...args): _Animator
    webkitMaskBoxImageSlice(...args): _Animator
    webkitMaskBoxImageSource(...args): _Animator
    webkitMaskBoxImageWidth(...args): _Animator
    webkitMaskClip(...args): _Animator
    webkitMaskComposite(...args): _Animator
    webkitMaskImage(...args): _Animator
    webkitMaskOrigin(...args): _Animator
    webkitMaskPosition(...args): _Animator
    webkitMaskPositionX(...args): _Animator
    webkitMaskPositionY(...args): _Animator
    webkitMaskRepeat(...args): _Animator
    webkitMaskRepeatX(...args): _Animator
    webkitMaskRepeatY(...args): _Animator
    webkitMaskSize(...args): _Animator
    webkitMaxLogicalHeight(...args): _Animator
    webkitMaxLogicalWidth(...args): _Animator
    webkitMinLogicalHeight(...args): _Animator
    webkitMinLogicalWidth(...args): _Animator
    webkitOpacity(...args): _Animator
    webkitOrder(...args): _Animator
    webkitPaddingAfter(...args): _Animator
    webkitPaddingBefore(...args): _Animator
    webkitPaddingEnd(...args): _Animator
    webkitPaddingStart(...args): _Animator
    webkitPerspective(...args): _Animator
    webkitPerspectiveOrigin(...args): _Animator
    webkitPerspectiveOriginX(...args): _Animator
    webkitPerspectiveOriginY(...args): _Animator
    webkitPrintColorAdjust(...args): _Animator
    webkitRtlOrdering(...args): _Animator
    webkitRubyPosition(...args): _Animator
    webkitShapeImageThreshold(...args): _Animator
    webkitShapeMargin(...args): _Animator
    webkitShapeOutside(...args): _Animator
    webkitTapHighlightColor(...args): _Animator
    webkitTextCombine(...args): _Animator
    webkitTextDecorationsInEffect(...args): _Animator
    webkitTextEmphasis(...args): _Animator
    webkitTextEmphasisColor(...args): _Animator
    webkitTextEmphasisPosition(...args): _Animator
    webkitTextEmphasisStyle(...args): _Animator
    webkitTextFillColor(...args): _Animator
    webkitTextOrientation(...args): _Animator
    webkitTextSecurity(...args): _Animator
    webkitTextSizeAdjust(...args): _Animator
    webkitTextStroke(...args): _Animator
    webkitTextStrokeColor(...args): _Animator
    webkitTextStrokeWidth(...args): _Animator
    webkitTransform(...args): _Animator
    webkitTransformOrigin(...args): _Animator
    webkitTransformOriginX(...args): _Animator
    webkitTransformOriginY(...args): _Animator
    webkitTransformOriginZ(...args): _Animator
    webkitTransformStyle(...args): _Animator
    webkitTransition(...args): _Animator
    webkitTransitionDelay(...args): _Animator
    webkitTransitionDuration(...args): _Animator
    webkitTransitionProperty(...args): _Animator
    webkitTransitionTiming(...args): _Animator
    webkitUserDrag(...args): _Animator
    webkitUserModify(...args): _Animator
    webkitUserSelect(...args): _Animator
    webkitWritingMode(...args): _Animator
    whiteSpace(...args): _Animator
    widows(...args): _Animator
    width(...args): _Animator
    willChange(...args): _Animator
    wordBreak(...args): _Animator
    wordSpacing(...args): _Animator
    wordWrap(...args): _Animator
    writingMode(...args): _Animator
    x(...args): _Animator
    y(...args): _Animator
    zIndex(...args): _Animator
    zoom(...args): _Animator
}
interface Element {
    //node: not all child functions may be available on all platforms. this set was generated using chrome 72.0.3626.121
    AnimatorJS(): _Animator
}
export function AnimatorJS(element?): _Animator;